// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin from "./routes/admin.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $Dashboard from "./islands/Dashboard.tsx";
import * as $MyDatePicker from "./islands/MyDatePicker.tsx";
import * as $MyLocationPicker from "./islands/MyLocationPicker.tsx";
import * as $signals_global_signals from "./islands/signals/global.signals.ts";
import * as $signals_location_signals from "./islands/signals/location.signals.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin.tsx": $admin,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/Dashboard.tsx": $Dashboard,
    "./islands/MyDatePicker.tsx": $MyDatePicker,
    "./islands/MyLocationPicker.tsx": $MyLocationPicker,
    "./islands/signals/global.signals.ts": $signals_global_signals,
    "./islands/signals/location.signals.ts": $signals_location_signals,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
