// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin from "./routes/admin.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $Card from "./islands/Card.tsx";
import * as $Dashboard from "./islands/Dashboard.tsx";
import * as $HydrateClientState from "./islands/HydrateClientState.tsx";
import * as $MyDatePicker from "./islands/MyDatePicker.tsx";
import * as $icons_Arrow from "./islands/icons/Arrow.tsx";
import * as $icons_ClockTimeLeft from "./islands/icons/ClockTimeLeft.tsx";
import * as $icons_Sun from "./islands/icons/Sun.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin.tsx": $admin,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/Card.tsx": $Card,
    "./islands/Dashboard.tsx": $Dashboard,
    "./islands/HydrateClientState.tsx": $HydrateClientState,
    "./islands/MyDatePicker.tsx": $MyDatePicker,
    "./islands/icons/Arrow.tsx": $icons_Arrow,
    "./islands/icons/ClockTimeLeft.tsx": $icons_ClockTimeLeft,
    "./islands/icons/Sun.tsx": $icons_Sun,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
